set(CMAKE_SYSTEM_NAME "Darwin")
set(CMAKE_SYSTEM_PROCESSOR "x86_64h")

set(TOOLCHAIN_PREFIX "${CMAKE_SYSTEM_PROCESSOR}-apple-darwin24")

set(TOOLCHAIN_PATH "$ENV{DARWIN_HOME}")

if ("${TOOLCHAIN_PATH}" STREQUAL "")
	set(TOOLCHAIN_PATH "${CMAKE_CURRENT_LIST_DIR}/../../../../..")
endif()

set(CMAKE_C_COMPILER "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-clang" CACHE FILEPATH "cc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-clang++" CACHE FILEPATH "c++")
set(CMAKE_AR "/usr/bin/llvm-ar" CACHE FILEPATH "ar")
set(CMAKE_RANLIB "/usr/bin/llvm-ranlib" CACHE FILEPATH "ranlib")
set(CMAKE_STRIP "/usr/bin/llvm-strip" CACHE FILEPATH "strip")
set(CMAKE_OBJCOPY "/usr/bin/llvm-objcopy" CACHE FILEPATH "objcopy")
set(CMAKE_OBJDUMP "/usr/bin/llvm-objdump" CACHE FILEPATH "objdump")
set(CMAKE_NM "/usr/bin/llvm-nm" CACHE FILEPATH "nm")

set(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_PATH}/SDK/MacOSX15.sdk" CACHE FILEPATH "sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
